### ISSUE TITLE
feature: Dump png files with alpha channel

### ISSUE THREAD

**Issue by Roker2** [n0samu/DirectorCastRipper#3]
I dumped game files, but so many png assets with white background, which is not correct.

**Comment by n0samu** [comment]
Hi, can you provide an example of a Director file affected by this issue, along with a specific cast member?

Older Director movies do not usually store bitmaps with an alpha channel. Instead, they store 24-bit or 8-bit bitmaps, which are displayed with transparency on the stage using the "background transparent" ink. This is one of Director's ink effects; it interprets a specific color (usually white) as the transparent color, kind of like chroma keying. Hope that makes sense!

**Comment by Roker2** [comment]
Oh. I thought it is a problem of the app. Hm, okay, thank you, I will try to use white color as chroma keying.

**Comment by n0samu** [comment]
I was just giving a general 'most likely' answer, but I can check whether Cast Ripper is working correctly with your specific Director file if you upload it.

**Comment by webfischi** [comment]
> Hi, can you provide an example of a Director file affected by this issue, along with a specific cast member?
> 
> Older Director movies do not usually store bitmaps with an alpha channel. Instead, they store 24-bit or 8-bit bitmaps, which are displayed with transparency on the stage using the "background transparent" ink. This is one of Director's ink effects; it interprets a specific color (usually white) as the transparent color, kind of like chroma keying. Hope that makes sense!

How will it chroma white, when the used asset is white? Most games I've seen between 1990 and 2010 usually use pink for chroma, like shown in #10
